### ISSUE TITLE
kubectl get nodes:The connection to the server 172.17.4.99:443 was refused - did you specify the right host or port?

### ISSUE THREAD

**Issue by jiamliang** [k8sp/vagrant-coreos#5]
按照文档：https://coreos.com/kubernetes/docs/latest/kubernetes-on-vagrant-single.html 进行时间的时候，vagrant up 正常，但执行 kubectl get nodes 返回错误:
The connection to the server 172.17.4.99:443 was refused - did you specify the right host or port?
### 环境

Ubuntu 16.04 64bit （Thinkpad X230i Windows 10 & Ubuntu 双系统）
### 操作步骤：

wget "https://releases.hashicorp.com/vagrant/1.8.1/vagrant_1.8.1_x86_64.deb"
sudo dpkg -i vagrant_1.8.1_x86_64.deb
curl -O https://storage.googleapis.com/kubernetes-release/release/v1.2.3/bin/linux/amd64/kubectl
chmod +x kubectl
sudo mv kubectl /usr/local/bin/kubectl 
sudo apt-get install virtualbox 
git clone https://github.com/coreos/coreos-kubernetes.git
cd coreos-kubernetes/single-node/
sed -i 's/alpha/beta/g' Vagrantfile
vagrant box update
vagrant up
# 下载太慢，改为手工下载box文件：http://beta.release.core-os.net/amd64-usr/1010.3.0/coreos_production_vagrant.box

vagrant box add my-coreos /home/liangjiameng/Downloads/coreos_production_vagrant.box
# 修改Vagrantfile： config.vm.box = "my-coreos"  注释随后两行（版本和url）

vagrant up
# vagrant up 后，virtualbox 报错。执行下面两行：

sudo modprobe vboxdrv
sudo modprobe vboxnetadp
# 再次执行 vagrant up 正常启动虚拟机

vagrant up
# 配置kubectl

export KUBECONFIG="${KUBECONFIG}:$(pwd)/kubeconfig"
kubectl config use-context vagrant-single
kubectl get nodes 
# 返回

The connection to the server 172.17.4.99:443 was refused - did you specify the right host or port?
### 其他信息：

$ ping 172.17.4.99  是通的
$ vagrant ssh
Last login: Sun May 15 14:59:07 2016 from 10.0.2.2
CoreOS beta (1010.3.0)
Failed Units: 2
  coreos-cloudinit-137139417.service
  update-engine.service

core@localhost ~ $ systemctl | grep kube      没有任何输出

**Comment by lipeng-unisound** [comment]
vagrant ssh 到 172.17.4.99（我没跑过 vagrant-single，不知道它的 hostname）。
docker ps 能否看到如下 docker container？

```
CONTAINER ID        IMAGE                                      COMMAND                  CREATED             STATUS              PORTS               NAMES
3fa4723d2856        quay.io/coreos/hyperkube:v1.2.4_coreos.1   "/hyperkube controlle"   About an hour ago   Up About an hour                        k8s_kube-controller-manager.20af0903_kube-controller-manager-172.17.4.101_kube-system_3ce6ac62028265327fc987444c8f73d1_17bcf365
ca4de4733123        quay.io/coreos/hyperkube:v1.2.4_coreos.1   "/hyperkube proxy --m"   About an hour ago   Up About an hour                        k8s_kube-proxy.ae2b61b3_kube-proxy-172.17.4.101_kube-system_7f8f464c17931de0b3771e01a604f50c_c24b867a
98539130aaf2        quay.io/coreos/hyperkube:v1.2.4_coreos.1   "/hyperkube scheduler"   About an hour ago   Up About an hour                        k8s_kube-scheduler.ce96e6_kube-scheduler-172.17.4.101_kube-system_6283345906d1fb1497bee62dac0f426a_76f4fc4e
170bfa76f83a        quay.io/coreos/hyperkube:v1.2.4_coreos.1   "/hyperkube apiserver"   About an hour ago   Up About an hour                        k8s_kube-apiserver.104a687e_kube-apiserver-172.17.4.101_kube-system_fa68ab5a32290a5aff7c08b4eafbab42_168a3e6f
d38ca5c623a1        gcr.io/google_containers/pause:2.0         "/pause"                 About an hour ago   Up About an hour                        k8s_POD.6059dfa2_kube-controller-manager-172.17.4.101_kube-system_3ce6ac62028265327fc987444c8f73d1_32e8878c
fd5fb7428d37        gcr.io/google_containers/pause:2.0         "/pause"                 About an hour ago   Up About an hour                        k8s_POD.6059dfa2_kube-proxy-172.17.4.101_kube-system_7f8f464c17931de0b3771e01a604f50c_0fc7849b
7cd043b536be        gcr.io/google_containers/pause:2.0         "/pause"                 About an hour ago   Up About an hour                        k8s_POD.6059dfa2_kube-scheduler-172.17.4.101_kube-system_6283345906d1fb1497bee62dac0f426a_f67eadc3
682bb803cf97        gcr.io/google_containers/pause:2.0         "/pause"                 About an hour ago   Up About an hour                        k8s_POD.6059dfa2_kube-apiserver-172.17.4.101_kube-system_fa68ab5a32290a5aff7c08b4eafbab42_e338444f
```

docker images 能否看到如下两个 images？

```
REPOSITORY                       TAG                 IMAGE ID            CREATED             SIZE
quay.io/coreos/hyperkube         v1.2.4_coreos.1     2cac344d3116        8 days ago          328.4 MB
gcr.io/google_containers/pause   2.0                 2b58359142b0        7 months ago        350.2 kB
```

**Comment by typhoonzero** [comment]
同样的问题。我的环境：MacOS + virtualbox

我这里运行之后，根据默认的配置会启动3个VM， e1(etcd), c1(master), w1(worker)。vagrant ssh e1之后ps -ef和docker ps没有看到etcd进程，到c1之后docker ps会卡住。

**Comment by typhoonzero** [comment]
Found something here: https://github.com/coreos/coreos-kubernetes/blob/master/Documentation/kubernetes-on-vagrant.md
**NOTE**: When the cluster is first launched, it must download all container images for the cluster components (Kubernetes, dns, heapster, etc). Depending on the speed of your connection, it can take a few minutes before the Kubernetes api-server is available. Before the api-server is running, the kubectl command above may show output similar to:

```
The connection to the server 172.17.4.101:443 was refused - did you specify the right host or port?
```

Maybe we need a different docker registry in China, or try to use proxies?

**Comment by wangkuiyi** [comment]
我也在好奇。我在w1上docker ps 看到了etcd。试图用etcdctl去连接，但是连不上。（我的vagrant Kubernetes机群是工作的，在host上可以用kubectl操作机群。）

**Comment by jiamliang** [comment]
这个问题产生是因为GFW。
在下载Flannel image的时候，由于被墙，导致后面一系列的操作都失败了。
后来，我在翻墙的网络中再次运行的时候，仍然出现相同的问题。这是因为之前被墙的时候，Vbox创建了三个有问题的虚拟机（ c1  e1  w1 ），当我在翻墙环境中执行vagrant up的时候，由于Vbox中已经存在了三个虚拟机，vagrant up 直接就启动虚拟机了，并没有进行像第一次执行vagrant up 一样，会去下载flannel Image。
正确的做法是：在翻墙的网络中 vagrant destroy 掉所有的虚拟机，再次 vagrant up。

感谢大家在解决这个问题过程中提供的各方面信息。谢谢！
